services:
  web:
    build:
      context: .
      dockerfile: web-src/Dockerfile
    container_name: LC-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  media:
    build:
      context: .
      dockerfile: media-src/Dockerfile
    container_name: LC-media
    ports:
      - "3000:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: LC-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: LC-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
